name: Build and Publish PMF Image
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*" # Tags de production
      - "v*.*.*-alpha" # Tags de test/alpha

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      # Logique pour choisir les variables selon le tag
      - name: Set Environment Variables
        id: set-vars
        run: |
          if [[ ${{ github.ref_name }} == *-alpha ]]; then
            echo "ENV_TYPE=ALPHA"
            echo "backend=${{ vars.ALPHA_NEXT_PUBLIC_BACKEND_URL }}" >> $GITHUB_OUTPUT
            echo "client_id=${{ vars.ALPHA_NEXT_PUBLIC_CLIENT_ID }}" >> $GITHUB_OUTPUT
            echo "frontend=${{ vars.ALPHA_NEXT_PUBLIC_FRONTEND_URL }}" >> $GITHUB_OUTPUT
          else
            echo "ENV_TYPE=PROD"
            echo "backend=${{ vars.NEXT_PUBLIC_BACKEND_URL }}" >> $GITHUB_OUTPUT
            echo "client_id=${{ vars.NEXT_PUBLIC_CLIENT_ID }}" >> $GITHUB_OUTPUT
            echo "frontend=${{ vars.NEXT_PUBLIC_FRONTEND_URL }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Node & Generate API
        run: |
          npm install @hey-api/openapi-ts@^0.88.0
          sed -i 's|http://127.0.0.1:8000|'"$NEXT_PUBLIC_BACKEND_URL"'|g' openapi-ts.config.ts
          npm run generate
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ steps.set-vars.outputs.backend }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ secrets.DOCKER_REGISTRY_IDENTIFER }}/pmf-frontend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=alpha,enable=${{ contains(github.ref_name, 'alpha') }}
            type=raw,value=latest,enable=${{ !contains(github.ref_name, 'alpha') }}

      - name: Login to Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push app
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ steps.set-vars.outputs.backend }}
            NEXT_PUBLIC_CLIENT_ID=${{ steps.set-vars.outputs.client_id }}
            NEXT_PUBLIC_FRONTEND_URL=${{ steps.set-vars.outputs.frontend }}
